### ISSUE TITLE
I can't open the settings

### ISSUE THREAD

**Issue by bamm1313** [IamWarHead/ddb-game-log#110]
I was DM'ing my group last night and as we were getting started, I went to add the mapping to the new players' characters. I don't know where I went wrong. I tried uninstalling and reinstalling the app as well. Is there anything I can do?

**Comment by IamWarHead** [comment]
Sorry for the late reply. You can find a workaround on the discord which can bypass the issue until I found a solution. I still cannot reproduce it so its quite hard to fix on my side. If you have please provide more informations how can I reproduce it. Thanks in advance!
