### ISSUE TITLE
Required field "content" not present in chat message

### ISSUE THREAD

**Issue by IamWarHead** [IamWarHead/ddb-game-log#15]
TheTreat was reporting this issue on discord:

```
Getting an error "Required field content not present in chat message" when I click roll from a character sheet
And the rolls being sent over are the raw rolls and not rolls with modifier
```

**Comment by rmasoni** [comment]
I have a very similar issue, but modifiers seem to be added properly.

```
main.js:1 Uncaught (in promise) Error: Required field content not present in ChatMessage.
```

I wish the module could show the roll and the modifiers separate as in core, so we could click to expand and see what was the result of the dice.

**Comment by IamWarHead** [comment]
> I have a very similar issue, but modifiers seem to be added properly.
> 
> ```
> main.js:1 Uncaught (in promise) Error: Required field content not present in ChatMessage.
> ```

Hey @rmasoni thank for reporting the issue! If you can please come to the [discord](https://discord.gg/HSTtrphyFg) server and we can continue the bug addressing process. It's a very nasty issue, I still cannot reproduce so if you have time just come and lets find together.

> I wish the module could show the roll and the modifiers separate as in core, so we could click to expand and see what was the result of the dice.

You can already. Some of the features requires patreon supporter membership. You can [check them here](https://www.patreon.com/iamwarhead/)
You can find an article about the Roll Result Breakdown feature [here](https://github.com/IamWarHead/ddb-game-log/wiki/Module-Features-%7C-Roll-results-breakdown)

**Comment by IamWarHead** [comment]
**Regarding @TheTreat 's report about missing modifiers:**

It seems beyond20 **breaks the official roll logic on dndbeyond.com**.

If beyond20's chrome extension is installed it blocks the official site to transfer the rolls to their websocket server so ddb-game-log's backend service wont be noticed when you roll.

Beyond20's roll parsing fails on modifiers thats why its not displayed in its chat message.

Unfortunately I cannot handle that issue, the only way to resolve this to completely uninstall beyond20's chrome extension.

I have marked beyond20 as a conflicting module in ddb-game-logs readme. I will add a notice message in Foundry in the next weekly release too.

**Comment by IamWarHead** [comment]
@rmasoni if you will have time could you please update the module to the latest (0.7.15) and could you please check the console regarding the issue?

@gazoir reported on discord that the error exists only if pending messages are turned on. If you can please verify this too.
On my end I still cannot reproduce the issue -.-"

**Comment by rmasoni** [comment]
Hey, I just updated but I still get that error. On top of it, I'm getting a `429` on a POST to Discord. What's the deal with that? What's being sent to Discord?

```
Error: Required field content not present in ChatMessage.
    at ChatMessage._validateRequiredField (/Users/rmasoni/Dropbox/RPG/FVTT/resources/app/dist/database/odm/abstract.js:1:4323)
    at ChatMessage.validate (/Users/rmasoni/Dropbox/RPG/FVTT/resources/app/dist/database/odm/abstract.js:1:3994)
    at ChatMessage.save (/Users/rmasoni/Dropbox/RPG/FVTT/resources/app/dist/database/odm/document.js:1:4895)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Function._onCreate (/Users/rmasoni/Dropbox/RPG/FVTT/resources/app/dist/database/odm/document.js:1:6989)
    at async Socket.handleEvent (/Users/rmasoni/Dropbox/RPG/FVTT/resources/app/dist/sockets.js:1:2262)
_handleError @ foundry.js:3780
(anonymous) @ foundry.js:3761
n.onack @ index.js:83
n.onpacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.ondecoded @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
a.add @ index.js:83
n.ondata @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
n.onData @ index.js:83
ws.onmessage @ index.js:83

main.js:1 Uncaught (in promise) TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
    at _0x254cbf.handlePendingRoll (main.js:1)
    at async _0x254cbf.onClientRoll (main.js:1)
handlePendingRoll @ main.js:1
async function (async)
onClientRoll @ main.js:1
onMessage @ main.js:1
(anonymous) @ main.js:1

main.js:1 POST https://discord.com/api/webhooks/814065463545954345/wPDqjWpE19AxY1HN-HV6dYrPDeFathoefbpjNp-VOma09Jja3h4eGkJLBsMxNUf-YbO7 429
yVXWD @ main.js:1
pTFsk @ main.js:1
YGskz @ main.js:1
(anonymous) @ main.js:1
_0x387d4f @ main.js:1
async function (async)
_0x387d4f @ main.js:1
yVXWD @ main.js:1
pTFsk @ main.js:1
_0x5c2d39 @ main.js:1
async function (async)
_0x5c2d39 @ main.js:1
ECkfh @ main.js:1
XzGnn @ main.js:1
handlePendingRoll @ main.js:1
async function (async)
handlePendingRoll @ main.js:1
onClientRoll @ main.js:1
async function (async)
onClientRoll @ main.js:1
onMessage @ main.js:1
(anonymous) @ main.js:1
```

**Comment by rmasoni** [comment]
Hey, I just updated but I still get that error. On top of it, I'm getting a `429` on a POST to Discord. What's the deal with that? What's being sent to Discord?

```
Error: Required field content not present in ChatMessage.
    at ChatMessage._validateRequiredField (/FVTT/resources/app/dist/database/odm/abstract.js:1:4323)
    at ChatMessage.validate (/FVTT/resources/app/dist/database/odm/abstract.js:1:3994)
    at ChatMessage.save (/FVTT/resources/app/dist/database/odm/document.js:1:4895)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Function._onCreate (/FVTT/resources/app/dist/database/odm/document.js:1:6989)
    at async Socket.handleEvent (/FVTT/resources/app/dist/sockets.js:1:2262)
_handleError @ foundry.js:3780
(anonymous) @ foundry.js:3761
n.onack @ index.js:83
n.onpacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.ondecoded @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
a.add @ index.js:83
n.ondata @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
n.onData @ index.js:83
ws.onmessage @ index.js:83

main.js:1 Uncaught (in promise) TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
    at _0x254cbf.handlePendingRoll (main.js:1)
    at async _0x254cbf.onClientRoll (main.js:1)
handlePendingRoll @ main.js:1
async function (async)
onClientRoll @ main.js:1
onMessage @ main.js:1
(anonymous) @ main.js:1

main.js:1 POST https://discord.com/api/webhooks/814065463545954345/wPDqjWpE19AxY1HN-HV6dYrPDeFathoefbpjNp-VOma09Jja3h4eGkJLBsMxNUf-YbO7 429
yVXWD @ main.js:1
pTFsk @ main.js:1
YGskz @ main.js:1
(anonymous) @ main.js:1
_0x387d4f @ main.js:1
async function (async)
_0x387d4f @ main.js:1
yVXWD @ main.js:1
pTFsk @ main.js:1
_0x5c2d39 @ main.js:1
async function (async)
_0x5c2d39 @ main.js:1
ECkfh @ main.js:1
XzGnn @ main.js:1
handlePendingRoll @ main.js:1
async function (async)
handlePendingRoll @ main.js:1
onClientRoll @ main.js:1
async function (async)
onClientRoll @ main.js:1
onMessage @ main.js:1
(anonymous) @ main.js:1
```

PS: I don't have Beyond20.

**Comment by IamWarHead** [comment]
hey, thanks for getting back. Discord issue happens now because i've added a discord hook to be able to address the issue. its sending the message payload when pending message error happens into a restricted channel on discord. so i can reproduce the exact same issue on my side. unfortunately i am not able to reproduce the issue on an other way. 

I was not assuming that amount of messages, so thats why you got too many requests error :(

I will try to fix it soon, and i hope pending messages issue will gone so i can remove the call of the discord hook.

Thanks for noticing me about 429 👍 

Have you tried to turn off the pending messages feature?

**Comment by rmasoni** [comment]
That's a weird workaround haha

Disabling “Display pending rolls” stops any error messages. Not sure if it's just hiding the problem or fixing it.

**Comment by IamWarHead** [comment]
> That's a weird workaround haha
> 
> Disabling “Display pending rolls” stops any error messages. Not sure if it's just hiding the problem or fixing it.

I was able to address that the issue is happening when a roll has a pending state. It is occurring when I am composing the message content for that kind of chat messages. It's a special type of message which has no content but a field called `flavour`. 

If you turn off pending rolls this error should not occur and it will not trigger the discord hook so Error 429 should gone also.

Still working on a fix, I hope I will be able to finish it today night. 

If you can please join to discord, it would be a huge help to me to have you on my side during the debug and fixing process.

Thank you again for everything, I will get back to you when I have progress.
I apologise for the inconviniences.

**Comment by rmasoni** [comment]
Hey, no worries. Not sure if I'll be able to assist you today, but I'll let you know if I join the server. Thanks for all the work on this mod.

**Comment by IamWarHead** [comment]
@rmasoni a possible fix has been deployed. When you will have some free time to burn on this issue please check `the release version 0.7.16` and let me know what happened :D 🤞 fingers crossed. thanks in advance! and I owe you one!

**Comment by IamWarHead** [comment]
Issue has been fixed.

**Kudos to @gazoir @thetreat @rmasoni** 👍
