### ISSUE TITLE
Invalid campaign ID

### ISSUE THREAD

**Issue by rmasoni** [IamWarHead/ddb-game-log#22]
I'm getting this error with the latest version. Tried with both the URL and just the ID. It was working fine before.

```
[DDB GAMELOG] Your Campaign ID entry seems to be invalid. Please set it again in the Core Settings panel. Your browser will reload in 10s.
```

After the reload it clears the campaign ID field from Core Settings.

**Comment by IamWarHead** [comment]
Can you send your uuid and campaign id to `warhead@warhead.hu` please?

Your uuid can be found in `core settings > debug`

Thanks in advance!

**Comment by IamWarHead** [comment]
I've got the issue. Will be fixed soon! Thanks for the report!

**Comment by rmasoni** [comment]
That was fast! Do you think it's possible to have it fixed today so I can delight my players with it? 😁

**Comment by IamWarHead** [comment]
@rmasoni i was restarting backend services right now. Can you try it please?

**Comment by IamWarHead** [comment]
@rmasoni ⚠️ If you were logged out and logged in on dnd beyond please do not forget to update your cobalt cookie in the core settings!

**Comment by rmasoni** [comment]
It worked! Thank you so much!

Is `v0.8.0` the latest version? I'm not getting those beautiful message styles shown in the tutorials. Mine look like this:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/62244/111067076-2462fc00-84a1-11eb-9f34-833b67e978a8.png">

**Comment by IamWarHead** [comment]
Im happy to hear that the issue has fixed.

Yes, 0.8.0 is the latest. Those features are tied to Patreon Support
membership levels.

You can check what memberships can offer on that link:

https://www.patreon.com/iamwarhead
