### ISSUE TITLE
Use player dice with Dice So Nice!

### ISSUE THREAD

**Issue by rmasoni** [IamWarHead/ddb-game-log#23]
This integration is great, but it'd be even better if the dice shown was the same as the player configured on their Dice So Nice! module settings.

**Comment by IamWarHead** [comment]
Im planning to rework the full message handling module (frontend) to avoid some edge cases with CUB / etc. When I will be finished with that It will be a configurable option in the DDB Gamelog Module settings. Thank you for the suggestion!

**Comment by IamWarHead** [comment]
Messages refact (#31) will fix that
