### ISSUE TITLE
Cannot transfer module ownership: Possible incompatibility with Forien's Copy Environment Module?

### ISSUE THREAD

**Issue by napolitanod** [IamWarHead/ddb-game-log#48]
Good morning,

Thank you for this great module

**Issue**
My issue is that I cannot configure ddb game log in a couple of my worlds and, when I select the transfer ownership to me button (shown in image attached), nothing happens - I get no response. When I select the 'take over module ownership' button I get the following error in the developers console of Chrome but it still launches the pop-up:
foundry.js:4481 TypeError: An error occurred while rendering _0x1fcd76 104: Cannot read property 'active' of null
    at _0x1fcd76.activateListeners (main.js:1)
    at _0x1fcd76._render (foundry.js:4537)
    at async _0x1fcd76._render (foundry.js:5157)

**Possible Cause?**
I am not 100% sure on this, but I think that this was caused when copying the ddb-game-log module configuration settings over from another world where it currently works great using Forien's Copy Environment module. I have several worlds and saw this occur when setting up one of them (so, when I set up the new world, I had no modules set up or configured in that new world and I used the Copy Environment to copy the settings from an existing world to the new world. In those settings it includes which modules are enabled and what their configurations are). My guess is, because the configs were done in this way there's some invalid state that the ddb game log module is in. If I remove the module from my world are readd it then I still get the error reported here. Though I learned that I cannot use the copy environment module to copy ddb game log settings, my existing worlds where I did this cannot make use of your module.

So, possibly not an error on your side but reporting it here should there be something in the transfer ownership of ddb game log that should be clearing out invalid data to allow for reconfiguring the ddb game log.

![image](https://user-images.githubusercontent.com/22696153/114196997-c3dfa700-9906-11eb-9666-31cf5cff2452.png)

**Comment by xdy** [comment]
If you are adventurous to the point of foolishness and beyond - which it turns out I am -  you can **AFTER TURNING OFF FOUNDRY AND BACKING UP YOUR WORLD** edit settings.db with a text editor to remove the line that looks like:
```
{"key":"ddb-game-log.moduleOwnership","value":"\"<somevalue>\"","_id":"<someothervalue>"}
```
**AND NOTHING ELSE**
Then save and close the file, start foundry, open your world (that you have a backup of, right?) and hopefully you can now edit the module settings again.
If not, restore the backup and wait for an official response. What can I say, it worked for me. :)

**Comment by IamWarHead** [comment]
@napolitanod why do you have that option? You are not the master Gm?

**Comment by IamWarHead** [comment]
Thanks for the info @xdy unfortunately Forge messes a lot with the official foundry settings / variables and values. I will check that issue as soon as I am done with the current development, maybe later this week.

**Comment by xdy** [comment]
The problem can occur locally. It did that for me after I had copied in all settings from one world to a new world.

**Comment by napolitanod** [comment]
@IamWarHead I am the master GM and I set up these worlds. Nobody else has had the permissions to configure anything in any of my worlds. This is happening in my local dev (on my laptop) and is happening on the server - I am self hosted on Amazon AWS and do not use Forge

Thanks!

Dan

**Comment by IamWarHead** [comment]
I tried it and I was able to reproduce the issue. It happens because the copy environment module. It copies all of your settings but your uuid is different in the new world, so my module thinks you are not the original game master. I will check is there an easy way to work around this issue, but its not on my side, it works as intended. I will get in touch with the developer of the other module.

**Comment by IamWarHead** [comment]
I will ask for your patience guys, it will take some time, but i will keep you informed.

**Comment by napolitanod** [comment]
Totally understandable. I expected that may be the case!

**Comment by IamWarHead** [comment]
I will begin to address the issue next week. Hopefully a fix will be out in the second half of the next week.

**Comment by IamWarHead** [comment]
possible workaround can be sending`game.settings.set("ddb-game-log", "moduleOwnership", game.user.id)` to the devtools console @napolitanod

**Comment by napolitanod** [comment]
Thank you for the update and workaround. I will give that a shot.

**Comment by IamWarHead** [comment]
> Thank you for the update and workaround. I will give that a shot.

You're welcome. I contacted the current maintainer of the Forien's Copy Environment module and he implemented a solution to let the module developers to opt-out their modules in his mod. I mean it will not be possible to copy the settings of the gamelog module anymore. It is the best way to keep everything as stable as we can with the module.

**Reference:** 
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/commit/0fe2aed085534c324cea622290c598c5ab6666ee

Thank you again for the bug report, and please consider to join my discord server (if you didnt joined yet)
**Discord:** https://discord.gg/HSTtrphyFg
