### ISSUE TITLE
Disadvantage roll with same value will sum them instead of pick one of them

### ISSUE THREAD

**Issue by whelan** [IamWarHead/ddb-game-log#82]
The result for if the roll is the same on both dices. The result is shown below
![Screen Shot 2021-07-13 at 17 28 08](https://user-images.githubusercontent.com/75122/125791223-e757808c-f222-4f55-bd4d-1dfbe4503c9e.png)

**Comment by IamWarHead** [comment]
It was fixed in ddb-game-log@2.1.11
