### ISSUE TITLE
Warning message in FoundryVTT from ddb-game-log

### ISSUE THREAD

**Issue by kriegtiger** [IamWarHead/ddb-game-log#87]
New install of FoundryVTT 0.8.9 went fine but reports this warning message in the logs during use. I contacted Foundry to inquire about the message and how to make it go away, they suggested I come here as the message originates from this module for the application. 

> It looks like that's a warning message coming from the DDB Game Log module. This would be an issue the developer of the module would have to fix (at least for it to be permanent). The only change necessary would be opening the 'module.json' file and trimming the trailing 's' off of the 'systems' key which was deprecated in a previous release.

![image](https://user-images.githubusercontent.com/6956044/137516032-2e99158b-f404-4b6b-9ecc-eab8f867dc6b.png)

**Comment by IamWarHead** [comment]
Thanks for the report @kriegtiger, im on it.

**Comment by IamWarHead** [comment]
It will be fixed in the upcoming release next week!

**Comment by IamWarHead** [comment]
It's in production. Could you please double check if the error still exists @kriegtiger ?

**Comment by kriegtiger** [comment]
Looks good. I was at version 1.4.2 until this morning, and it said 1.5.0 was available - checked the timestamp of the module.json file that I had manually edited before and it was updated as of this morning after running the update.

The word was 'system' instead of 'systems' in the file and the foundry generated no warnings on startup/load of the game world that used the module.

**Comment by IamWarHead** [comment]
Perfect! Thank you again!
